### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by drewtom** [Courier-Online/cojm#273]
Hi am new to programming so please bare with me Lol.I managed to install to a point where i need database structure, How do i create database structure?

**Comment by Courier-Online** [comment]
Hi drewton, already on ticket #203 , there were 20 changes to it yesterday so not ready to upload yet, will be changing too much. See https://github.com/Courier-Online/cojm/milestone/1
Steve

**Comment by drewtom** [comment]
ohh ok,Thanks man. waiting for it..XD
